#!/usr/bin/env bash
set -euo pipefail

BUILD_TYPE=${BUILD_TYPE:-Release}
BUILD_DIR=${BUILD_DIR:-build}
INSTALL_PREFIX=${INSTALL_PREFIX:-${BUILD_DIR}/install}
OCR_LINK_CXX_STATIC=${OCR_LINK_CXX_STATIC:-AUTO}
OCR_ENABLE_SERVER=${OCR_ENABLE_SERVER:-OFF}
OCR_BUILD_SERVER_EXECUTABLE=${OCR_BUILD_SERVER_EXECUTABLE:-OFF}
BUILD_JOBS=$(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1)

rm -rf "${BUILD_DIR}"

echo "==> Building RapidOcrOnnx"
echo "    BUILD_TYPE=${BUILD_TYPE}"
echo "    OCR_ENABLE_SERVER=${OCR_ENABLE_SERVER}"
echo "    OCR_BUILD_SERVER_EXECUTABLE=${OCR_BUILD_SERVER_EXECUTABLE}"
cmake -S . -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
  -DOCR_LINK_CXX_STATIC="${OCR_LINK_CXX_STATIC}" \
  -DOCR_ENABLE_SERVER="${OCR_ENABLE_SERVER}" \
  -DOCR_BUILD_SERVER_EXECUTABLE="${OCR_BUILD_SERVER_EXECUTABLE}"
cmake --build "${BUILD_DIR}" -j"${BUILD_JOBS}"
cmake --install "${BUILD_DIR}"
echo "==> Done. Installed to ${INSTALL_PREFIX}"
